"""third commit

Revision ID: 7d0918acc677
Revises: a6fe3d8bcd51
Create Date: 2024-11-07 17:32:27.740225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0918acc677'
down_revision: Union[str, None] = 'a6fe3d8bcd51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pumps', sa.Column('pump_name', sa.String(length=25), nullable=True))
    op.add_column('sensors', sa.Column('sensor_name', sa.String(length=25), nullable=True))
    op.add_column('shifts', sa.Column('shift_name', sa.String(length=25), nullable=True))
    op.add_column('timers', sa.Column('timer_name', sa.String(length=25), nullable=True))
    op.add_column('valves', sa.Column('valve_name', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valves', 'valve_name')
    op.drop_column('timers', 'timer_name')
    op.drop_column('shifts', 'shift_name')
    op.drop_column('sensors', 'sensor_name')
    op.drop_column('pumps', 'pump_name')
    # ### end Alembic commands ###
